# Generated by Django 3.1.3 on 2021-01-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='jsonlink',
            new_name='OfficialSiteURL',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='site_url',
            new_name='jsonLink',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='teamname',
            new_name='locationName',
        ),
        migrations.AddField(
            model_name='team',
            name='teamName',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
