# Generated by Django 3.1.3 on 2021-03-21 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'ordering': ['-id'], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
