# Generated by Django 3.1.3 on 2021-05-16 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardType',
            fields=[
                ('board', models.CharField(choices=[('Scoreboards', (('mlb', 'MLB'), ('nfl', 'NFL'), ('nhl', 'NHL'))), ('Custom', (('custom1', 'Custom1'),))], default='nhl', max_length=16, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Board Type',
                'verbose_name_plural': 'Board Types',
                'db_table': 'boardTypes',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'ordering': ['-id'], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterField(
            model_name='settings',
            name='name',
            field=models.CharField(default='Custom Profile Name', max_length=32, verbose_name='Config Name'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='settings',
            name='boardType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scoreboard.boardtype'),
            preserve_default=False,
        ),
    ]
