# Generated by Django 3.1.3 on 2021-01-31 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='config',
            field=models.JSONField(default=dict),
        ),
    ]
