# Generated by Django 3.1.3 on 2021-01-26 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='configJSON',
            new_name='config',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='boards',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='debug',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='live_mode',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='loglevel',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='preferences',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='sbio',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='states',
        ),
    ]
