# Generated by Django 3.1.3 on 2021-01-26 04:20

from django.db import migrations, models
import scoreboard.models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_auto_20210125_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='config',
            field=models.JSONField(default=scoreboard.models.Settings.conf_default),
        ),
    ]
