# Generated by Django 3.1.3 on 2021-03-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_auto_20210321_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='name',
            field=models.CharField(default='Custom Profile Name', max_length=32, verbose_name='Config Name'),
        ),
    ]
