# Generated by Django 3.1.3 on 2021-01-31 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_auto_20210130_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='path_to_file',
        ),
        migrations.AlterField(
            model_name='settings',
            name='config',
            field=models.JSONField(default={'boards': {'clock': {'clock_rgb': '', 'date_rgb': '', 'duration': 15, 'flash_seconds': True, 'hide_indicator': False, 'preferred_team_colors': True}, 'covid19': {'canada_enabled': False, 'canada_prov': ['Quebec'], 'country': ['USA'], 'country_enabled': False, 'us_state': ['New York'], 'us_state_enabled': False, 'worldwide_enabled': False}, 'scoreticker': {'preferred_teams_only': False, 'rotation_rate': 5}, 'seriesticker': {'preferred_teams_only': True, 'rotation_rate': 5}, 'standings': {'conference': 'eastern', 'divisions': 'central', 'preferred_standings_only': True, 'standing_type': 'wild_card'}, 'weather': {'data_feed': 'EC', 'duration': 60, 'enabled': False, 'forecast_days': 3, 'forecast_enabled': True, 'forecast_update': 1, 'owm_apikey': '', 'show_on_clock': True, 'units': 'metric', 'update_freq': 5, 'view': 'full'}, 'wxalert': {'alert_duration': 5, 'alert_feed': 'EC', 'alert_title': True, 'nws_show_expire': False, 'scroll_alert': True, 'show_alerts': True, 'show_on_clock': True, 'update_freq': 5}}, 'debug': False, 'live_mode': False, 'loglevel': 'WARNING', 'preferences': {'end_of_day': '8:00', 'goal_animations': {'pref_team_only': True}, 'live_game_refresh_rate': 10, 'location': '', 'sog_display_frequency': 4, 'teams': ['Blackhawks'], 'time_format': '12h'}, 'sbio': {'dimmer': {'daytime': '', 'enabled': False, 'frequency': 5, 'light_level_lux': 400, 'mode': 'always', 'nighttime': '', 'offset': 90, 'source': 'software', 'sunrise_brightness': 40, 'sunset_brightness': 5}, 'pushbutton': {'bonnet': False, 'display_halt': True, 'display_reboot': True, 'enabled': False, 'pin': 25, 'poweroff_duration': 10, 'poweroff_override_process': '', 'reboot_duration': 2, 'reboot_override_process': '', 'state_triggered1': 'weather', 'state_triggered1_process': ''}, 'screensaver': {'animations': True, 'data_updates': False, 'delay': 30, 'enabled': True, 'motionsensor': True, 'pin': 24, 'start': '22:00', 'stop': '22:05'}}, 'states': {'intermission': ['scoreticker'], 'off_day': ['scoreticker', 'standings', 'clock'], 'post_game': ['standings', 'scoreticker', 'clock'], 'scheduled': ['standings', 'scoreticker', 'clock']}}),
        ),
    ]
