# Generated by Django 3.1.3 on 2021-01-25 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_auto_20210124_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='OfficialSiteURL',
            new_name='OfficialSiteUrl',
        ),
    ]
