# Generated by Django 3.1.3 on 2021-05-16 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_auto_20210516_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='boardType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scoreboard.boardtype'),
        ),
    ]
