# Generated by Django 3.1.3 on 2021-01-25 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0003_auto_20210124_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='OfficialSiteUrl',
            new_name='officialSiteUrl',
        ),
    ]
