# Generated by Django 3.1.3 on 2021-05-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0004_auto_20210516_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardtype',
            name='board',
            field=models.CharField(choices=[('Scoreboards', (('mlb', 'MLB'), ('nfl', 'NFL'), ('nhl', 'NHL'))), ('Custom', (('custom1', 'Custom1'),))], default='nhl', max_length=16, primary_key=True, serialize=False, unique=True),
        ),
    ]
