# Generated by Django 3.1.3 on 2021-01-25 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0004_auto_20210124_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='locationName',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='teamName',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
