# Generated by Django 3.1.3 on 2021-01-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0006_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='default_config',
            field=models.JSONField(default='scoreboard/fixtures/config.json.sample'),
        ),
    ]
