# Generated by Django 3.1.3 on 2021-01-25 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0007_settings_default_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='data',
            field=models.JSONField(default='dict()'),
        ),
    ]
