# Generated by Django 3.1.3 on 2021-01-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0009_auto_20210124_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='data',
            field=models.JSONField(default='{}'),
        ),
    ]
