# Generated by Django 3.1.3 on 2021-01-25 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0012_auto_20210124_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='default_config',
            field=models.JSONField(verbose_name='scoreboard/fixtures/config.json.sample'),
        ),
    ]
