# Generated by Django 3.1.3 on 2021-01-25 03:02

from django.db import migrations, models
import scoreboard.models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0013_auto_20210124_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Settings', 'verbose_name_plural': 'Settings'},
        ),
        migrations.AlterField(
            model_name='settings',
            name='default_config',
            field=models.JSONField(default=scoreboard.models.Settings.conf_default),
        ),
    ]
