# Generated by Django 3.1.3 on 2021-01-25 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0014_auto_20210124_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='data',
        ),
    ]
