# Generated by Django 3.1.3 on 2021-01-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0015_remove_settings_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='default_config',
            new_name='config',
        ),
        migrations.AddField(
            model_name='settings',
            name='isActive',
            field=models.BooleanField(default=1, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='settings',
            name='name',
            field=models.CharField(blank=True, max_length=32, verbose_name='Config Name'),
        ),
    ]
