# Generated by Django 3.1.3 on 2021-01-25 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0016_auto_20210124_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='name',
            field=models.CharField(blank=True, default='Default', max_length=32, verbose_name='Config Name'),
        ),
    ]
