# Generated by Django 3.1.3 on 2020-12-14 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_location_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Profiles'},
        ),
    ]
