# Generated by Django 3.1.3 on 2020-12-16 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20201214_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created',
            new_name='timestamp',
        ),
    ]
