# Generated by Django 3.1.3 on 2020-12-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_auto_20201218_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
    ]
