# Generated by Django 3.1.3 on 2021-01-04 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0023_auto_20201230_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followinglist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='following_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
