# Generated by Django 3.1.3 on 2020-11-25 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='end_date',
        ),
    ]
