# Generated by Django 3.1.3 on 2020-11-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='all_bids',
            field=models.ManyToManyField(blank=True, related_name='all_bids', to='auctions.Bid'),
        ),
    ]
