# Generated by Django 3.1.3 on 2020-11-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_listing_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='image_URL',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='start_price',
            field=models.DecimalField(decimal_places=2, default='00.00', max_digits=12),
        ),
        migrations.AlterField(
            model_name='listing',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
