# Generated by Django 3.1.3 on 2020-11-29 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bid_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='all_bids',
        ),
    ]
