# Generated by Django 3.1.3 on 2020-11-29 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_listing_all_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='all_bids',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_bids', to='auctions.bid'),
        ),
    ]
