# Generated by Django 3.1.3 on 2020-11-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20201128_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='total_bids',
        ),
        migrations.AddField(
            model_name='listing',
            name='all_bids',
            field=models.ManyToManyField(blank=True, null=True, related_name='all_bids', to='auctions.Bid'),
        ),
    ]
