# Generated by Django 3.1.3 on 2020-11-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20201128_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='all_bids',
        ),
        migrations.AddField(
            model_name='listing',
            name='total_bids',
            field=models.IntegerField(default=0),
        ),
    ]
