# Generated by Django 3.1.3 on 2020-11-29 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20201128_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='current_bid',
            field=models.OneToOneField(blank=True, default=models.DecimalField(decimal_places=2, default='00.00', max_digits=12), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_bid', to='auctions.bid'),
        ),
    ]
