# Generated by Django 3.1.3 on 2020-11-29 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20201128_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='listing_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_list', to='auctions.listing'),
        ),
    ]
