# Generated by Django 3.1.3 on 2020-11-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20201129_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='winning_bid',
            field=models.BooleanField(default=0),
        ),
    ]
