# Generated by Django 3.1.3 on 2020-11-29 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_listing_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='status',
            new_name='active_status',
        ),
    ]
