# Generated by Django 3.1.3 on 2020-11-29 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20201129_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='active_status',
            new_name='is_active',
        ),
    ]
