# Generated by Django 3.1.3 on 2020-11-29 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20201129_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='total_bids',
        ),
    ]
