# Generated by Django 3.1.3 on 2020-11-29 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20201129_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='current_bid',
            field=models.OneToOneField(blank=True, default=models.DecimalField(decimal_places=2, default='00.00', max_digits=12), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_bid', to='auctions.bid'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('items', models.ManyToManyField(related_name='categories', to='auctions.Listing')),
            ],
        ),
    ]
