# Generated by Django 3.1.3 on 2020-11-30 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_auto_20201129_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='item_list', to='auctions.Listing'),
        ),
    ]
