# Generated by Django 3.1.3 on 2020-11-30 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_auto_20201129_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='current_bid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_bid', to='auctions.bid'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='start_bid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
